### PR TITLE
problem: tx filter does not work

### LINKED ISSUE #390: all/in/out transaction filter not working

### LINKED ISSUE #396: transaction history search not working

### PR DESCRIPTION
**Pull request by shanejonas**
ALSO:

problem: tx search does not work

filter_search2

fixes #390
fixes #396

### CODE REVIEW

File: src/components/tx/TxHistory/history.js [hunk 1]
```diff
@@ -7,31 +7,99 @@ import { List } from 'immutable';
...
+  constructor(props) {
+    super(props);
+    this.state = {
+      txFilter: 'ALL',
+      displayedTransactions: this.props.transactions,
+    };
+  }
+  onSearchChange(e) {
+    const value = e.target.value;
+    const filteredTxes = this.props.transactions.filter((tx) => {
```
Comment (shanejonas) [inline src/components/tx/TxHistory/history.js]: i've been reading up on reselect. looking to refactor code like this to use that in the future.

**Comment by gagarin55** [comment]
Can we take out filter logic and write unit test for it? Otherwise it decrease code coverage
